"""Deterministic MITRE ATT&CK / ATLAS technique matching for threats.

No LLM involved — mirrors backend.rules.engine.match_patterns(): a pure,
offline lookup against the technique catalogs generated by
scripts/build_techniques.py into seeds/techniques/.

Three sources of truth, cheapest/most-trusted first:
1. Dependency-sourced threats (source == "dependency"): a fixed table keyed
   on dependency_ref.rule_id. No embedding call.
2. Rule-engine-sourced threats (source == "rule_engine"): the originating
   seed pattern's name often embeds a technique ID in parentheses
   (seeds/attack_cloud_patterns.json, seeds/atlas_patterns.json), extracted
   by regex.
3. Everything else (LLM-sourced, seeded): embedding similarity against the
   catalog, narrowed by a STRIDE/MAESTRO category -> tactic prior.
"""

import json
import logging
import re
from functools import lru_cache
from pathlib import Path
from typing import Any, Literal

from backend.config import settings
from backend.db.vectors import embed_text
from backend.dedup import cosine_similarity
from backend.models.enums import MaestroCategory, StrideCategory
from backend.models.state import TechniqueRef, Threat
from backend.rules.engine import extract_keywords


logger = logging.getLogger(__name__)

_CATALOG_DIR = Path(__file__).parent.parent.parent / "seeds" / "techniques"
_CATALOG_FILES = ("attack_enterprise.json", "atlas.json")

TOP_K = 3
# A weak noise filter, not a correctness signal: the golden-set test shows
# wrong candidates score as high as right ones (0.37-0.85 observed across
# both), so this cannot distinguish a good match from a bad one. It only
# trims the very weakest tail. Trustworthiness is communicated by
# TechniqueRef.method ("embedding" is always presented as a suggestion,
# never as confirmed), not by this threshold.
MIN_CONFIDENCE = 0.45

# Seed-pattern technique IDs embedded in a pattern's name, e.g.
# "Cloud Account Takeover ... (T1078.004)" or "ML Training Data Poisoning
# Attack (AML.T0020)". Compound IDs like "(AML.T0020+AML.T0057)" are not
# matched by this pattern and fall through to embedding matching instead.
_SEED_NAME_ID_RE = re.compile(r"\(((?:T\d{4}(?:\.\d{3})?)|(?:AML\.T\d{4}(?:\.\d{3})?))\)")

# Dependency-engine rule_id -> [(technique_id, confidence), ...]. IDs here
# must exist in the generated catalog — scripts/build_techniques.py's
# _ATTACK_EXPLICIT_INCLUDE guarantees it (and resolves MITRE renumbering
# automatically). Confidence reflects how directly the capability signal
# maps to the technique, not detection certainty.
DEPENDENCY_RULE_TECHNIQUES: dict[str, list[tuple[str, float]]] = {
    # Tarball ships code not present in the public source repo.
    "drift_signal": [("T1195.002", 0.9)],
    # A new npm lifecycle (install-time) script appeared in this version.
    "install_hook_added": [("T1059", 0.9)],
    # An npm lifecycle script is present (not necessarily new).
    "install_hook_present": [("T1059", 0.7)],
    # Obfuscated/dynamic eval, Function(), aliased require, etc.
    "dynamic_code": [("T1027", 0.75)],
    # Package reads env vars and makes outbound network calls — a secret-
    # exfiltration-capable shape, not a confirmed action, hence lower
    # confidence and two candidate techniques.
    "network_environment": [("T1552", 0.5), ("T1567", 0.5)],
    # Native/FFI bindings load compiled code outside the normal JS module
    # path — closest enterprise analog is reflective code loading.
    "native_ffi": [("T1620", 0.6)],
}

# STRIDE/MAESTRO category -> ATT&CK/ATLAS tactic display name(s), used only
# to narrow embedding-similarity candidates. Neither enum maps 1:1 onto a
# single tactic; if a category's listed tactics match nothing in the
# catalog the matcher falls back to the full catalog rather than returning
# zero candidates.
_STRIDE_TACTIC_PRIOR: dict[StrideCategory, list[str]] = {
    StrideCategory.SPOOFING: ["Initial Access", "Credential Access", "Defense Evasion", "Stealth"],
    StrideCategory.TAMPERING: ["Persistence", "Defense Impairment", "Defense Evasion", "Impact"],
    StrideCategory.REPUDIATION: ["Defense Impairment", "Stealth", "Defense Evasion"],
    StrideCategory.INFORMATION_DISCLOSURE: [
        "Collection",
        "Exfiltration",
        "Discovery",
        "Credential Access",
    ],
    StrideCategory.DENIAL_OF_SERVICE: ["Impact"],
    StrideCategory.ELEVATION_OF_PRIVILEGE: ["Privilege Escalation", "Execution"],
}

_MAESTRO_TACTIC_PRIOR: dict[MaestroCategory, list[str]] = {
    MaestroCategory.MODEL_SECURITY: [
        "AI Attack Staging",
        "Exfiltration",
        "Impact",
        "AI Model Access",
    ],
    MaestroCategory.DATA_SECURITY: ["Collection", "Exfiltration", "Credential Access"],
    MaestroCategory.LLM_SECURITY: ["Initial Access", "AI Model Access", "Execution", "Discovery"],
    MaestroCategory.PRIVACY: ["Collection", "Exfiltration"],
    MaestroCategory.SUPPLY_CHAIN: ["Resource Development", "Initial Access"],
    MaestroCategory.RESOURCE_ABUSE: ["Impact"],
    MaestroCategory.PIPELINE_SECURITY: [
        "Persistence",
        "Defense Evasion",
        "Execution",
        "Defense Impairment",
    ],
    MaestroCategory.REINFORCEMENT_LEARNING: ["AI Attack Staging", "Impact"],
    MaestroCategory.DISTRIBUTED_ML: ["Lateral Movement", "Impact"],
    MaestroCategory.MONITORING: ["Defense Impairment", "Stealth", "Defense Evasion"],
    MaestroCategory.INTERPRETABILITY: ["Reconnaissance", "AI Model Access"],
    MaestroCategory.AUTOML: ["Resource Development"],
    MaestroCategory.FAIRNESS: ["Impact"],
}


@lru_cache(maxsize=1)
def _load_catalog() -> list[dict[str, Any]]:
    """Load and flatten both technique catalog files, once per process.

    Each technique is tagged with its source file's `embedding_model`
    header (None if the file predates that header, e.g. a hand-edited
    catalog) — `_embedded_catalog()` only trusts a precomputed `embedding`
    vector when that tag matches the currently configured embedding
    model, so switching EMBEDDING_MODEL can't silently produce either a
    dimension-mismatch crash or (same dimension, different model)
    meaningless matches with no warning at all.
    """
    techniques: list[dict[str, Any]] = []
    for filename in _CATALOG_FILES:
        path = _CATALOG_DIR / filename
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as e:
            logger.warning(f"Failed to load technique catalog {path}: {e}")
            continue
        catalog_model = payload.get("embedding_model")
        if catalog_model is not None and catalog_model != settings.embedding_model:
            logger.warning(
                f"{path.name}'s precomputed embeddings were built with {catalog_model!r}, "
                f"not the configured {settings.embedding_model!r} — recomputing its "
                f"{len(payload.get('techniques', []))} techniques instead of using them."
            )
        for tech in payload.get("techniques", []):
            tech["_catalog_embedding_model"] = catalog_model
            techniques.append(tech)
    return techniques


@lru_cache(maxsize=1)
def _catalog_by_id() -> dict[str, dict[str, Any]]:
    return {t["id"]: t for t in _load_catalog()}


@lru_cache(maxsize=1)
def _embedded_catalog() -> list[tuple[dict[str, Any], tuple[float, ...], frozenset[str]]]:
    """Catalog entries paired with their embedding and keyword set, computed once.

    Prefers a precomputed `embedding` field (written by
    scripts/build_techniques.py) so a fresh process doesn't pay the cost of
    embedding the full catalog (~340 entries, ~9s) on its first pipeline
    run or CLI invocation — but only when the catalog file's recorded
    `embedding_model` matches the currently configured one; otherwise a
    stale/foreign vector would either crash cosine_similarity (different
    dimension) or silently produce meaningless matches (same dimension,
    different model). Falls back to embedding on the fly for catalog
    entries with no precomputed vector or a model mismatch — the offline
    fallback catalog, a hand-edited one, or a changed EMBEDDING_MODEL.
    """
    result = []
    for tech in _load_catalog():
        text = f"{tech['name']}. {tech.get('description', '')}"
        precomputed = tech.get("embedding")
        usable = precomputed and tech.get("_catalog_embedding_model") == settings.embedding_model
        try:
            embedding = tuple(precomputed) if usable else tuple(embed_text(text))
        except (ValueError, RuntimeError) as e:
            logger.warning(f"Failed to embed technique {tech.get('id')}: {e}")
            continue
        result.append((tech, embedding, frozenset(extract_keywords(text))))
    return result


def _hybrid_score(
    threat_embedding: list[float],
    threat_keywords: set[str],
    embedding: tuple[float, ...],
    keywords: frozenset[str],
) -> float:
    """Cosine similarity blended with keyword-set overlap.

    Pure cosine similarity over short technical descriptions ranks closely
    related techniques (e.g. sibling "cloud account" sub-techniques) within
    a few hundredths of each other — too close to reliably separate (see the
    map_techniques golden-set test). Blending in extract_keywords() overlap
    — the same security/tech-term keyword set the deterministic rule engine
    already uses — measurably improves ranking because technique names and
    threat descriptions share domain vocabulary (IAM, S3, container, etc.)
    even when the embedding model doesn't weight it heavily.
    """
    cos = cosine_similarity(threat_embedding, list(embedding))
    if not threat_keywords or not keywords:
        overlap = 0.0
    else:
        overlap = len(threat_keywords & keywords) / len(threat_keywords | keywords)
    return 0.6 * cos + 0.4 * overlap


def _technique_ref(
    tech: dict[str, Any], confidence: float, method: Literal["table", "seed", "embedding"]
) -> TechniqueRef:
    return TechniqueRef(
        id=tech["id"],
        name=tech["name"],
        url=tech.get("url", ""),
        confidence=round(min(max(confidence, 0.0), 1.0), 2),
        method=method,
    )


def _dependency_techniques(threat: Threat) -> list[TechniqueRef]:
    rule_id = threat.dependency_ref.rule_id if threat.dependency_ref else None
    if not rule_id:
        return []
    by_id = _catalog_by_id()
    refs = []
    for tech_id, confidence in DEPENDENCY_RULE_TECHNIQUES.get(rule_id, []):
        tech = by_id.get(tech_id)
        if tech is not None:
            refs.append(_technique_ref(tech, confidence, "table"))
    return refs


def _rule_engine_techniques(threat: Threat) -> list[TechniqueRef]:
    match = _SEED_NAME_ID_RE.search(threat.name)
    if not match:
        return []
    tech_id = match.group(1)
    tech = _catalog_by_id().get(tech_id)
    if tech is None:
        logger.info(f"Seed pattern references unresolved technique id {tech_id}")
        return []
    return [_technique_ref(tech, 0.95, "seed")]


def _tactic_prior(threat: Threat) -> list[str]:
    tactics = list(_STRIDE_TACTIC_PRIOR.get(threat.stride_category, []))
    # MaestroCategory isn't carried on Threat directly; nothing to add here
    # without it, but kept as a documented extension point for a future
    # maestro_category field on Threat.
    return tactics


def _embedding_match(threat: Threat) -> list[TechniqueRef]:
    embedded = _embedded_catalog()
    if not embedded:
        return []

    text = f"{threat.name}. {threat.description} Target: {threat.target}."
    try:
        threat_embedding = embed_text(text)
    except (ValueError, RuntimeError) as e:
        logger.warning(f"Failed to embed threat for technique matching: {e}")
        return []
    threat_keywords = extract_keywords(text)

    prior_tactics = set(_tactic_prior(threat))
    candidates = embedded
    if prior_tactics:
        narrowed = [(t, e, k) for t, e, k in embedded if prior_tactics & set(t.get("tactics", []))]
        if narrowed:
            candidates = narrowed

    scored = [
        (tech, _hybrid_score(threat_embedding, threat_keywords, embedding, keywords))
        for tech, embedding, keywords in candidates
    ]
    scored.sort(key=lambda pair: pair[1], reverse=True)

    return [
        _technique_ref(tech, score, "embedding")
        for tech, score in scored[:TOP_K]
        if score >= MIN_CONFIDENCE
    ]


def match_techniques(threat: Threat) -> list[TechniqueRef]:
    """Return the best MITRE ATT&CK/ATLAS technique matches for a threat.

    Pure and deterministic given the same catalog and embedding model;
    chooses the cheapest applicable source (dependency table, rule-engine
    regex, embedding similarity) rather than always embedding.
    """
    if threat.source == "dependency":
        return _dependency_techniques(threat)
    if threat.source == "rule_engine":
        matched = _rule_engine_techniques(threat)
        if matched:
            return matched
        # Fall through to embedding matching for seed patterns with no
        # parenthesized ID (most non-ATT&CK/ATLAS seed collections).
    return _embedding_match(threat)
