"""Migration 0001 — initial schema.

Creates every table, index, and the threat_vectors virtual table that existed
up to (and including) SCHEMA_VERSION = 2.  ADD COLUMN patches are applied
idempotently so the migration is safe to run against a database that was
created before the ledger system existed.

Do NOT edit this file after it has been applied to any production database.
To change the schema, create a new migration file (0003_…, 0004_…, …).
"""

import logging

import aiosqlite


logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# CREATE TABLE statements (snapshot of schema at migration creation time)
# ---------------------------------------------------------------------------

_THREAT_MODELS = """
CREATE TABLE IF NOT EXISTS threat_models (
    id              TEXT PRIMARY KEY,
    title           TEXT NOT NULL,
    description     TEXT,
    framework       TEXT DEFAULT 'STRIDE',
    provider        TEXT NOT NULL,
    model           TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'pending',
    iteration_count INTEGER DEFAULT 1,
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL,
    code_source_id  TEXT REFERENCES code_sources(id) ON DELETE SET NULL,
    created_by      TEXT,
    gap_summaries   TEXT,
    code_summary    TEXT,
    assumptions     TEXT,
    project_id      TEXT REFERENCES projects(id)
)
"""

_THREATS = """
CREATE TABLE IF NOT EXISTS threats (
    id                      TEXT PRIMARY KEY,
    model_id                TEXT NOT NULL,
    stride_category         TEXT,
    maestro_category        TEXT,
    name                    TEXT NOT NULL,
    description             TEXT NOT NULL,
    target                  TEXT NOT NULL,
    impact                  TEXT NOT NULL,
    likelihood              TEXT NOT NULL,
    dread_damage            INTEGER,
    dread_reproducibility   INTEGER,
    dread_exploitability    INTEGER,
    dread_affected_users    INTEGER,
    dread_discoverability   INTEGER,
    dread_score             REAL,
    mitigations             TEXT NOT NULL,
    status                  TEXT NOT NULL DEFAULT 'pending',
    iteration_number        INTEGER DEFAULT 1,
    created_at              TEXT NOT NULL,
    updated_at              TEXT NOT NULL,
    FOREIGN KEY (model_id) REFERENCES threat_models(id) ON DELETE CASCADE
)
"""

_ASSETS = """
CREATE TABLE IF NOT EXISTS assets (
    id           TEXT PRIMARY KEY,
    model_id     TEXT NOT NULL,
    type         TEXT NOT NULL,
    name         TEXT NOT NULL,
    description  TEXT NOT NULL,
    user_edited  INTEGER DEFAULT 0,
    created_at   TEXT NOT NULL,
    FOREIGN KEY (model_id) REFERENCES threat_models(id) ON DELETE CASCADE
)
"""

_FLOWS = """
CREATE TABLE IF NOT EXISTS flows (
    id               TEXT PRIMARY KEY,
    model_id         TEXT NOT NULL,
    flow_type        TEXT NOT NULL,
    flow_description TEXT NOT NULL,
    source_entity    TEXT NOT NULL,
    target_entity    TEXT NOT NULL,
    user_edited      INTEGER DEFAULT 0,
    created_at       TEXT NOT NULL,
    FOREIGN KEY (model_id) REFERENCES threat_models(id) ON DELETE CASCADE
)
"""

_TRUST_BOUNDARIES = """
CREATE TABLE IF NOT EXISTS trust_boundaries (
    id            TEXT PRIMARY KEY,
    model_id      TEXT NOT NULL,
    purpose       TEXT NOT NULL,
    source_entity TEXT NOT NULL,
    target_entity TEXT NOT NULL,
    user_edited   INTEGER DEFAULT 0,
    created_at    TEXT NOT NULL,
    FOREIGN KEY (model_id) REFERENCES threat_models(id) ON DELETE CASCADE
)
"""

_THREAT_SOURCES = """
CREATE TABLE IF NOT EXISTS threat_sources (
    id          TEXT PRIMARY KEY,
    model_id    TEXT NOT NULL,
    category    TEXT NOT NULL,
    description TEXT NOT NULL,
    example     TEXT NOT NULL,
    created_at  TEXT NOT NULL,
    FOREIGN KEY (model_id) REFERENCES threat_models(id) ON DELETE CASCADE
)
"""

_ATTACK_TREES = """
CREATE TABLE IF NOT EXISTS attack_trees (
    id            TEXT PRIMARY KEY,
    threat_id     TEXT NOT NULL,
    mermaid_source TEXT NOT NULL,
    created_at    TEXT NOT NULL,
    FOREIGN KEY (threat_id) REFERENCES threats(id) ON DELETE CASCADE
)
"""

_TEST_CASES = """
CREATE TABLE IF NOT EXISTS test_cases (
    id             TEXT PRIMARY KEY,
    threat_id      TEXT NOT NULL,
    gherkin_source TEXT NOT NULL,
    created_at     TEXT NOT NULL,
    FOREIGN KEY (threat_id) REFERENCES threats(id) ON DELETE CASCADE
)
"""

_THREAT_METADATA = """
CREATE TABLE IF NOT EXISTS threat_metadata (
    id              TEXT PRIMARY KEY,
    threat_id       TEXT,
    source          TEXT NOT NULL,
    embedding_model TEXT NOT NULL,
    vector_rowid    INTEGER,
    project_id      TEXT REFERENCES projects(id),
    created_at      TEXT NOT NULL,
    FOREIGN KEY (threat_id) REFERENCES threats(id) ON DELETE CASCADE
)
"""

_PIPELINE_RUNS = """
CREATE TABLE IF NOT EXISTS pipeline_runs (
    id          TEXT PRIMARY KEY,
    model_id    TEXT NOT NULL,
    iteration   INTEGER NOT NULL,
    step        TEXT NOT NULL,
    input_hash  TEXT NOT NULL,
    output_hash TEXT NOT NULL,
    provider    TEXT NOT NULL,
    tokens_used INTEGER,
    duration_ms INTEGER NOT NULL,
    created_at  TEXT NOT NULL,
    FOREIGN KEY (model_id) REFERENCES threat_models(id) ON DELETE CASCADE
)
"""

_CONFIG = """
CREATE TABLE IF NOT EXISTS config (
    key        TEXT PRIMARY KEY,
    value      BLOB NOT NULL,
    encrypted  INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL
)
"""

_CODE_SOURCES = """
CREATE TABLE IF NOT EXISTS code_sources (
    id                TEXT PRIMARY KEY,
    name              TEXT NOT NULL,
    git_url           TEXT NOT NULL,
    ref               TEXT,
    pat_ciphertext    BLOB,
    pat_last_used_at  TEXT,
    last_indexed_at   TEXT,
    last_index_status TEXT,
    last_index_error  TEXT,
    resolved_sha      TEXT,
    created_by        TEXT,
    created_at        TEXT NOT NULL,
    updated_at        TEXT NOT NULL,
    UNIQUE (git_url, ref)
)
"""

_USERS = """
CREATE TABLE IF NOT EXISTS users (
    id            TEXT PRIMARY KEY,
    username      TEXT NOT NULL,
    email         TEXT NOT NULL,
    display_name  TEXT,
    password_hash TEXT,
    is_active     INTEGER NOT NULL DEFAULT 1,
    is_admin      INTEGER NOT NULL DEFAULT 0,
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL,
    last_login_at TEXT
)
"""

_SESSIONS = """
CREATE TABLE IF NOT EXISTS sessions (
    id         TEXT PRIMARY KEY,
    user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    revoked_at TEXT
)
"""

_PERSONAL_ACCESS_TOKENS = """
CREATE TABLE IF NOT EXISTS personal_access_tokens (
    id          TEXT PRIMARY KEY,
    user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    token_hash  TEXT NOT NULL,
    project_id  TEXT,
    last_used_at TEXT,
    expires_at  TEXT,
    created_at  TEXT NOT NULL
)
"""

_PROJECTS = """
CREATE TABLE IF NOT EXISTS projects (
    id                  TEXT PRIMARY KEY,
    name                TEXT NOT NULL,
    description         TEXT,
    default_provider    TEXT,
    default_model       TEXT,
    default_iterations  INTEGER,
    default_temperature REAL,
    is_archived         INTEGER NOT NULL DEFAULT 0,
    created_by          TEXT REFERENCES users(id) ON DELETE SET NULL,
    created_at          TEXT NOT NULL,
    updated_at          TEXT NOT NULL
)
"""

_PROJECT_MEMBERS = """
CREATE TABLE IF NOT EXISTS project_members (
    id         TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role       TEXT NOT NULL CHECK(role IN ('owner', 'editor', 'viewer')),
    created_at TEXT NOT NULL,
    UNIQUE(project_id, user_id)
)
"""

_PROJECT_INVITATIONS = """
CREATE TABLE IF NOT EXISTS project_invitations (
    id            TEXT PRIMARY KEY,
    project_id    TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    invited_email TEXT NOT NULL,
    role          TEXT NOT NULL CHECK(role IN ('owner', 'editor', 'viewer')),
    invited_by    TEXT REFERENCES users(id) ON DELETE SET NULL,
    status        TEXT NOT NULL DEFAULT 'pending'
                       CHECK(status IN ('pending', 'accepted', 'declined', 'expired')),
    created_at    TEXT NOT NULL,
    expires_at    TEXT NOT NULL,
    UNIQUE(project_id, invited_email)
)
"""

_COMMENTS = """
CREATE TABLE IF NOT EXISTS comments (
    id               TEXT PRIMARY KEY,
    threat_model_id  TEXT NOT NULL REFERENCES threat_models(id) ON DELETE CASCADE,
    user_id          TEXT REFERENCES users(id) ON DELETE SET NULL,
    parent_id        TEXT REFERENCES comments(id) ON DELETE CASCADE,
    body             TEXT NOT NULL,
    created_at       TEXT NOT NULL,
    updated_at       TEXT NOT NULL
)
"""

_THREAT_MODEL_ASSIGNEES = """
CREATE TABLE IF NOT EXISTS threat_model_assignees (
    id               TEXT PRIMARY KEY,
    threat_model_id  TEXT NOT NULL REFERENCES threat_models(id) ON DELETE CASCADE,
    user_id          TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    assigned_by      TEXT REFERENCES users(id) ON DELETE SET NULL,
    created_at       TEXT NOT NULL,
    UNIQUE(threat_model_id, user_id)
)
"""

_ACTIVITY_LOG = """
CREATE TABLE IF NOT EXISTS activity_log (
    id          TEXT PRIMARY KEY,
    project_id  TEXT REFERENCES projects(id) ON DELETE CASCADE,
    user_id     TEXT REFERENCES users(id) ON DELETE SET NULL,
    entity_type TEXT NOT NULL,
    entity_id   TEXT NOT NULL,
    action      TEXT NOT NULL,
    details     TEXT,
    created_at  TEXT NOT NULL
)
"""

_NOTIFICATIONS = """
CREATE TABLE IF NOT EXISTS notifications (
    id          TEXT PRIMARY KEY,
    user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type        TEXT NOT NULL,
    title       TEXT NOT NULL,
    body        TEXT,
    entity_type TEXT,
    entity_id   TEXT,
    is_read     INTEGER NOT NULL DEFAULT 0,
    created_at  TEXT NOT NULL
)
"""

_INDICES = [
    "CREATE INDEX IF NOT EXISTS idx_threats_model_id ON threats(model_id);",
    "CREATE INDEX IF NOT EXISTS idx_threats_status ON threats(status);",
    "CREATE INDEX IF NOT EXISTS idx_threats_stride ON threats(stride_category);",
    "CREATE INDEX IF NOT EXISTS idx_assets_model_id ON assets(model_id);",
    "CREATE INDEX IF NOT EXISTS idx_flows_model_id ON flows(model_id);",
    "CREATE INDEX IF NOT EXISTS idx_pipeline_runs_model_id ON pipeline_runs(model_id);",
    "CREATE INDEX IF NOT EXISTS idx_threat_metadata_threat_id ON threat_metadata(threat_id);",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username ON users(username COLLATE NOCASE);",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(email COLLATE NOCASE);",
    "CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);",
    "CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_pat_hash ON personal_access_tokens(token_hash);",
    "CREATE INDEX IF NOT EXISTS idx_pat_user_id ON personal_access_tokens(user_id);",
    "CREATE INDEX IF NOT EXISTS idx_project_members_project_id ON project_members(project_id);",
    "CREATE INDEX IF NOT EXISTS idx_project_members_user_id ON project_members(user_id);",
    "CREATE INDEX IF NOT EXISTS idx_project_invitations_email ON project_invitations(invited_email);",
    "CREATE INDEX IF NOT EXISTS idx_threat_models_project_id ON threat_models(project_id);",
    "CREATE INDEX IF NOT EXISTS idx_code_sources_project_id ON code_sources(project_id);",
    "CREATE INDEX IF NOT EXISTS idx_comments_model_id ON comments(threat_model_id);",
    "CREATE INDEX IF NOT EXISTS idx_comments_parent_id ON comments(parent_id);",
    "CREATE INDEX IF NOT EXISTS idx_assignees_model_id ON threat_model_assignees(threat_model_id);",
    "CREATE INDEX IF NOT EXISTS idx_assignees_user_id ON threat_model_assignees(user_id);",
    "CREATE INDEX IF NOT EXISTS idx_threat_metadata_project ON threat_metadata(project_id);",
    "CREATE INDEX IF NOT EXISTS idx_activity_project_created ON activity_log(project_id, created_at);",
    "CREATE INDEX IF NOT EXISTS idx_activity_user_created ON activity_log(user_id, created_at);",
    "CREATE INDEX IF NOT EXISTS idx_activity_entity ON activity_log(entity_type, entity_id);",
    "CREATE INDEX IF NOT EXISTS idx_notifications_user_read_created "
    "ON notifications(user_id, is_read, created_at);",
]

# Columns added by inline ALTER TABLE patches in early versions.
# On fresh databases these already exist (CREATE TABLE includes them).
# On upgrade paths the try/except makes this idempotent.
_ADD_COLUMN_PATCHES = [
    "ALTER TABLE threat_models ADD COLUMN code_source_id TEXT "
    "REFERENCES code_sources(id) ON DELETE SET NULL",
    "ALTER TABLE threat_models ADD COLUMN created_by TEXT",
    "ALTER TABLE threat_models ADD COLUMN gap_summaries TEXT",
    "ALTER TABLE threat_models ADD COLUMN code_summary TEXT",
    "ALTER TABLE threat_models ADD COLUMN assumptions TEXT",
    "ALTER TABLE threat_metadata ADD COLUMN vector_rowid INTEGER",
    "ALTER TABLE assets ADD COLUMN user_edited INTEGER DEFAULT 0",
    "ALTER TABLE flows ADD COLUMN user_edited INTEGER DEFAULT 0",
    "ALTER TABLE trust_boundaries ADD COLUMN user_edited INTEGER DEFAULT 0",
    "ALTER TABLE threat_models ADD COLUMN project_id TEXT REFERENCES projects(id)",
    "ALTER TABLE code_sources ADD COLUMN project_id TEXT REFERENCES projects(id)",
    "ALTER TABLE threat_metadata ADD COLUMN project_id TEXT REFERENCES projects(id)",
]


async def up(conn: aiosqlite.Connection) -> None:
    """Create all tables, apply ADD COLUMN patches, create indices.

    Must NOT call BEGIN or COMMIT — the runner owns the transaction.
    """
    # Tables with forward-reference ordering (code_sources before threat_models
    # for the FK on code_source_id, projects before threat_metadata for its FK).
    for sql in (
        _CONFIG,
        _CODE_SOURCES,
        _USERS,
        _SESSIONS,
        _PERSONAL_ACCESS_TOKENS,
        _PROJECTS,
        _PROJECT_MEMBERS,
        _PROJECT_INVITATIONS,
        _THREAT_MODELS,
        _THREATS,
        _ASSETS,
        _FLOWS,
        _TRUST_BOUNDARIES,
        _THREAT_SOURCES,
        _ATTACK_TREES,
        _TEST_CASES,
        _THREAT_METADATA,
        _PIPELINE_RUNS,
        _COMMENTS,
        _THREAT_MODEL_ASSIGNEES,
        _ACTIVITY_LOG,
        _NOTIFICATIONS,
    ):
        await conn.execute(sql)

    # ADD COLUMN patches for columns added after the original v1 schema.
    # On fresh databases all these columns are already present (CREATE TABLE includes them);
    # the OperationalError on "duplicate column name" is caught and skipped.
    for sql in _ADD_COLUMN_PATCHES:
        try:
            await conn.execute(sql)
        except aiosqlite.OperationalError as exc:
            if "duplicate column name" not in str(exc).lower():
                raise

    # Defensive backfill for threat_metadata rows predating the project_id column.
    await conn.execute("""
        UPDATE threat_metadata SET project_id = (
            SELECT tm.project_id FROM threats t
            JOIN threat_models tm ON tm.id = t.model_id
            WHERE t.id = threat_metadata.threat_id
        ) WHERE project_id IS NULL AND source != 'seed'
    """)

    # Indices
    for sql in _INDICES:
        await conn.execute(sql)

    # Vector table — requires sqlite-vec extension; skip gracefully if unavailable.
    try:
        await conn.execute("""
            CREATE VIRTUAL TABLE IF NOT EXISTS threat_vectors
            USING vec0(embedding float[384])
        """)
    except Exception:
        logger.warning("sqlite-vec extension not available — threat_vectors table not created")
