"""Migration 0002 — Default Project backfill (v1 → v2 data migration).

Existing threat_models and code_sources that lack a project_id are assigned
to an auto-created 'Default Project' (sentinel UUID
00000000-0000-0000-0000-000000000000).  The admin user, if present, becomes
the owner.

On fresh databases this is a structural no-op: no threat_models exist yet, so
the backfill updates 0 rows.  The Default Project row is inserted once via
OR IGNORE, providing a stable home for any threat models created before the
user sets up their first explicit project.

Do NOT edit this file after it has been applied to any production database.
"""

import logging
import uuid
from datetime import UTC, datetime

import aiosqlite


logger = logging.getLogger(__name__)

_DEFAULT_PROJECT_ID = "00000000-0000-0000-0000-000000000000"


async def up(conn: aiosqlite.Connection) -> None:
    """Backfill project_id on existing threat_models and code_sources.

    Must NOT call BEGIN or COMMIT — the runner owns the transaction.
    """
    now = datetime.now(UTC).isoformat()

    # Resolve admin user (may not exist on a brand-new instance).
    async with conn.execute("SELECT id FROM users WHERE username = 'admin' LIMIT 1") as cur:
        row = await cur.fetchone()
    admin_id = row[0] if row else None

    # Create Default Project (OR IGNORE makes this idempotent).
    await conn.execute(
        """
        INSERT OR IGNORE INTO projects
            (id, name, description, is_archived, created_by, created_at, updated_at)
        VALUES
            (?, 'Default Project', 'Automatically created on first startup', 0, ?, ?, ?)
        """,
        (_DEFAULT_PROJECT_ID, admin_id, now, now),
    )

    # Backfill threat_models and code_sources that have no project.
    await conn.execute(
        "UPDATE threat_models SET project_id = ? WHERE project_id IS NULL",
        (_DEFAULT_PROJECT_ID,),
    )
    await conn.execute(
        "UPDATE code_sources SET project_id = ? WHERE project_id IS NULL",
        (_DEFAULT_PROJECT_ID,),
    )

    # Add admin as owner of Default Project (OR IGNORE — idempotent).
    if admin_id:
        await conn.execute(
            """
            INSERT OR IGNORE INTO project_members
                (id, project_id, user_id, role, created_at)
            VALUES
                (?, ?, ?, 'owner', ?)
            """,
            (str(uuid.uuid4()), _DEFAULT_PROJECT_ID, admin_id, now),
        )
        logger.info("Migration 0002: Default Project owner set to admin (%s)", admin_id)

    logger.info("Migration 0002: Default Project backfill complete")
