"""Migration 0003 — Add source/confidence to threats, staleness threshold to projects.

Supports three new features:
- Threat source tracking (LLM vs rule-engine) for bulk review filtering
- Confidence scoring on generated threats
- Per-project staleness notification threshold

Do NOT edit this file after it has been applied to any production database.
"""

import logging

import aiosqlite


logger = logging.getLogger(__name__)


async def up(conn: aiosqlite.Connection) -> None:
    # -- threats.source: origin of each threat ('llm' or 'rule_engine')
    try:
        await conn.execute("ALTER TABLE threats ADD COLUMN source TEXT DEFAULT 'llm'")
    except Exception:
        logger.debug("Column threats.source already exists, skipping")

    # -- threats.confidence: grounding score 0.0-1.0, nullable for old threats
    try:
        await conn.execute("ALTER TABLE threats ADD COLUMN confidence REAL")
    except Exception:
        logger.debug("Column threats.confidence already exists, skipping")

    # -- projects.staleness_threshold_days: per-project staleness notification window
    try:
        await conn.execute(
            "ALTER TABLE projects ADD COLUMN staleness_threshold_days INTEGER DEFAULT 30"
        )
    except Exception:
        logger.debug("Column projects.staleness_threshold_days already exists, skipping")
