"""Migration 0005 — Add dependency provenance to threats, and a dependency_scans table.

Supports the dependency capability engine feeding the threat pipeline
(Week 3): a threat with source="dependency" carries a `dependency_ref` JSON
blob (package/version/file/line/rule_id), and each analyzed package's raw
capability analysis is persisted per model for the Dependencies UI tab.

Do NOT edit this file after it has been applied to any production database.
"""

import logging

import aiosqlite


logger = logging.getLogger(__name__)


async def up(conn: aiosqlite.Connection) -> None:
    # -- threats.dependency_ref: JSON {package, version, file, line, rule_id},
    # set only when threats.source == "dependency".
    try:
        await conn.execute("ALTER TABLE threats ADD COLUMN dependency_ref TEXT")
    except Exception:
        logger.debug("Column threats.dependency_ref already exists, skipping")

    await conn.execute(
        """
        CREATE TABLE IF NOT EXISTS dependency_scans (
            id TEXT PRIMARY KEY,
            model_id TEXT NOT NULL,
            package TEXT NOT NULL,
            version TEXT NOT NULL,
            source_mode TEXT NOT NULL,
            analysis TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (model_id) REFERENCES threat_models(id) ON DELETE CASCADE
        )
        """
    )
    await conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_dependency_scans_model ON dependency_scans(model_id)"
    )
