"""Migration 0006 — Wire usage accounting into pipeline_runs.

Adds `model` (the identifier the step was actually routed to) and the four
token-count columns (`input_tokens`, `output_tokens`, `cache_read_tokens`,
`cache_write_tokens`) reported by backend/providers/usage.py. The table and
its `tokens_used`/`provider`/`duration_ms` columns already existed
(migration 0001) but had no caller — this migration doesn't touch them.

No prices anywhere: tokens are reported by step and by model, and the
dollar figure for any routing claim is computed once, outside the product,
from cited published rates (decided 2026-10-01).

Do NOT edit this file after it has been applied to any production database.
"""

import logging

import aiosqlite


logger = logging.getLogger(__name__)

_NEW_COLUMNS = (
    ("model", "TEXT"),
    ("input_tokens", "INTEGER"),
    ("output_tokens", "INTEGER"),
    ("cache_read_tokens", "INTEGER"),
    ("cache_write_tokens", "INTEGER"),
)


async def up(conn: aiosqlite.Connection) -> None:
    for name, sql_type in _NEW_COLUMNS:
        try:
            await conn.execute(f"ALTER TABLE pipeline_runs ADD COLUMN {name} {sql_type}")
        except Exception:
            logger.debug("Column pipeline_runs.%s already exists, skipping", name)
