"""Migration 0007 — Persist the run's token-usage report on threat_models.

The pipeline_runs audit rows (0006) are per-step detail; `usage_summary` is
the same `RunUsage` JSON (backend/models/usage.py) the COMPLETE SSE event
already carries, persisted once per run so the Results page's "Run summary"
card survives a page reload — mirroring how `gap_summaries` and
`code_summary` are persisted from that same event.

Do NOT edit this file after it has been applied to any production database.
"""

import logging

import aiosqlite


logger = logging.getLogger(__name__)


async def up(conn: aiosqlite.Connection) -> None:
    try:
        await conn.execute("ALTER TABLE threat_models ADD COLUMN usage_summary TEXT")
    except Exception:
        logger.debug("Column threat_models.usage_summary already exists, skipping")
