"""Migration 0008 — Persist uploaded architecture diagrams.

The run route already builds a `DiagramData` (backend/models/extended.py) from
an uploaded PNG/JPG/Mermaid file and feeds it straight into the pipeline; it
was never stored anywhere, so a page reload or the Results diagram tab had
nothing to show. `model_diagrams` holds one row per diagram (several rows
per model are supported, even though this week only ever writes one — Week
5a's multi-diagram UI builds on this table as-is).

A diagram is user input, not pipeline output: it is replaced only when a new
one is actually uploaded (backend/routes/models.py's `_persist_diagram_data`,
via `crud.replace_model_diagram`, which deletes the old row(s) and inserts
the new one in a single commit), never wiped by `crud.clear_model_data()` on
a re-run or re-extract that didn't upload one.

Do NOT edit this file after it has been applied to any production database.
"""

import aiosqlite


async def up(conn: aiosqlite.Connection) -> None:
    await conn.execute(
        """
        CREATE TABLE IF NOT EXISTS model_diagrams (
            id TEXT PRIMARY KEY,
            model_id TEXT NOT NULL,
            name TEXT NOT NULL,
            kind TEXT NOT NULL CHECK (kind IN ('mermaid', 'png', 'jpeg')),
            content TEXT NOT NULL,
            media_type TEXT,
            size_bytes INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (model_id) REFERENCES threat_models(id) ON DELETE CASCADE
        )
        """
    )
    await conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_model_diagrams_model_id ON model_diagrams(model_id)"
    )
