"""Migration 0009 — Add ATT&CK/ATLAS technique matches to threats.

Supports the deterministic map_techniques pipeline step (Week 4b-2): every
threat gets an `attack_techniques` JSON blob — a list of
{id, name, url, confidence} — matched after the rule-engine and dependency
merges, regardless of threat source (llm/rule_engine/dependency/seeded).

Do NOT edit this file after it has been applied to any production database.
"""

import logging

import aiosqlite


logger = logging.getLogger(__name__)


async def up(conn: aiosqlite.Connection) -> None:
    # -- threats.attack_techniques: JSON list of
    # {id, name, url, confidence}, set by the map_techniques pipeline step.
    try:
        await conn.execute("ALTER TABLE threats ADD COLUMN attack_techniques TEXT")
    except Exception:
        logger.debug("Column threats.attack_techniques already exists, skipping")
