"""Migration 0010 — CVSS v3.1 scoring alongside DREAD (Week 4b-3).

Adds:
- threats.cvss_vector: the canonical "AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
  base-metric string — set by the LLM (when scoring_method includes
  "cvss"), the deterministic dependency-threat default-vector table, or a
  reviewer's manual edit.
- threats.cvss_score / threats.cvss_severity: always computed server-side
  by backend.scoring.cvss31.score_and_severity() from cvss_vector, never
  trusted from a provider response (see Threat.cvss_score/cvss_severity's
  SkipJsonSchema + force-compute in generate_threats()). Cached here
  rather than recomputed on every read, matching dread_score alongside the
  five dread_* columns.
- threat_models.scoring_method: "dread" | "cvss" | "both", chosen at
  model-creation time. NULL on every pre-existing row (this migration adds
  the column with no default); every write path from here on (crud.create_
  threat_model, persist.py, the web run route) passes an explicit value —
  "dread" unless the caller opted into "cvss"/"both" — and the one read
  path that matters today (backend/routes/models.py's run route) treats a
  NULL/missing value as "dread", so existing models and scripts are
  unaffected.

Do NOT edit this file after it has been applied to any production database.
"""

import logging

import aiosqlite


logger = logging.getLogger(__name__)


async def up(conn: aiosqlite.Connection) -> None:
    for ddl in (
        "ALTER TABLE threats ADD COLUMN cvss_vector TEXT",
        "ALTER TABLE threats ADD COLUMN cvss_score REAL",
        "ALTER TABLE threats ADD COLUMN cvss_severity TEXT",
        "ALTER TABLE threat_models ADD COLUMN scoring_method TEXT",
    ):
        try:
            await conn.execute(ddl)
        except Exception:
            logger.debug("Column from %r already exists, skipping", ddl)
