"""Migration 0011 — ordered multi-diagram storage (Week 5a-1).

Adds `model_diagrams.position`, an explicit ordering column. Before this,
`list_model_diagrams` ordered by `created_at DESC` only — fine for a single
stored diagram, but rows inserted together in one `replace_model_diagrams`
transaction can share a timestamp, so creation order alone can't be trusted
to preserve the order the caller uploaded them in.

Existing rows default to position=0 (they're all one row per model today,
so there's nothing to reorder). `replace_model_diagrams` sets position
explicitly on every new insert.

Do NOT edit this file after it has been applied to any production database.
"""

import logging

import aiosqlite


logger = logging.getLogger(__name__)


async def up(conn: aiosqlite.Connection) -> None:
    try:
        await conn.execute(
            "ALTER TABLE model_diagrams ADD COLUMN position INTEGER NOT NULL DEFAULT 0"
        )
    except Exception:
        logger.debug("model_diagrams.position already exists, skipping")
